language: en
version: "3.6"          

pipeline:
  # Basic tokenisation / regex helpers
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: RegexEntityExtractor


  # BERT / RoBERTa / DistilBERT via Hugging-Face
- name: LanguageModelFeaturizer
  model_name: "bert"                # bert | roberta | distilbert …
  model_weights: "bert-base-uncased"

  # DIET now consumes the BERT embeddings
- name: DIETClassifier
  epochs: 60
  constrain_similarities: true

  # Post-processing
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 30
- name: FallbackClassifier
  threshold: 0.30

policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 200
assistant_id: 20250620-142129-objective-edge
